apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCa+QldGa8vDskxG2nqgHUjlZn68a8BPD8qUHC2xgrorcvZfmY/U7khAYEUwkmWfpiV2B3yiSQOSO6ZybbDZM6/7J3pY1Eu5CnEQ+BqKLkXoMt/tPaRhrEqvicsqJScHK5C3udqHsMNAyV5bJaGKuTjrBkVh58/z3q/AZn31tO/bKEHejer8FqpPmD+VnKaH6x46VpSlgorzgoKQkFoNMLsCXDZrJXkJpL+Ex1gD8pUJxD5xwAD1Eeut/+NLI7RZqsjiZnQThNWnGEfSVv29CN2DInF5kz/YZ/P/jKIinqwjT9o+8OixSZvoiejWQhg5YFgU0dQNQJgpRAHVJ3NuaObGk3V+7xqjxOAC09YtCI4KSgzMTDWiXNCcBIRJXg/OJI8xTypL6nqRCc7cVrbwyRCb15xMmuyOMteyNvYrWjgs3OS6q9gcXzvshu3ZblNyB3Bo+Zj16XvwCJJwYs4BCwDTX2VPvNMVha3tEo+yt21Bsd9FmsUzajJsV+kdrr4jsuM02E0i3IjyNVTyl6wT7jmh9pQTOQT4KHW38hy30ESb14sio0gI1s2VdCPTaq1PJ2dGx2lB84CBmfQTRUUMVNSDNce15751bBEtES8RuL2Wt9PTcffZybffez7Z3zsBdzZtDGq6Vlf4eolxVNIBZveQ1EnWnOuUILTm1U4uiLocMQWjMyG+eEO+lUBJebFJtt9865pfJ0D9+uRZ850/hyiUNmgxg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
