apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAuYIpE95wOqYppQtcupdCJx3aCF6DxQBi4jucVWqD9mYVjAhebiW3djtThwTLghgp58kgRFS0sT0bXO1+V+npT2ySjIt6ocbLk4KrHFEYMCOFmyVrt/0jZU94036fKv2jLHDM2gpk5Fl84BzqCTXhKfE9Ydwtw/RweifcVxYbZinov/qwcIkZjeaHzwzsRhQkbtbZNU+ulJVsVRZiSthRm1EN+UIuyrhUezsR8rY4Pp8kGuZkOJK6Qb57eSYoTGFx/+nPyEMXuJ1uaDQS9ZFWt1xVCCHvequXU7jD0Qwv+dDHc0HJEQuZ0g22rzM22l1fL8TOMIfCWV9WkfhZQpoOcY8v/ytK/aiYk7POJEE2X0kdfyC3aXe0/eaigeDjsgx5KY43Jnfjc+RiH5kGbQLhIr3su3lp5StPowb7Sd+wruOAJU0L4JY0MRLFQNx1dK5/MBscSej4r96ZMisuQD7AWcisGShY1jjI5yE5iLb/jeAujTeEN92+GZB9qmJ6gSDklxrxBZqfitBo9iJ42/T0LBJp69dUPyZxzHASBduJEcQ7IXUh6BcWXdxjaacNud4on3a17MEjoc/alVfBpMNKp3Y/GDqKF6dvrGWY2CJvc2PTjeEm1sOlCcHJ9UmezDsY4hBOZUW+HtKmD2xRysDgpzy1Oihmrw5LZ9qR66FLPutSDtrEar387+OTNxqsbylaou7nwMq7CYgAJxQHYJnUuqpGsag==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
